# Generated by Django 6.0 on 2025-12-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'offre")),
                ('description', models.TextField(verbose_name='Description')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation / Entreprise')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_opp', models.CharField(max_length=100, verbose_name='Type (Formation, Bourse, Appel à projet)')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisateur')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
